# Generated by Django 5.2.16 on 2026-07-12 15:37

import secrets

import cloud_pos.models
import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import djmoney.money
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def _backfill_qr_tokens(apps, schema_editor):
    POSTable = apps.get_model('cloud_pos', 'POSTable')
    used = set(POSTable.objects.exclude(qr_token='').values_list('qr_token', flat=True))
    for table in POSTable.objects.all().iterator():
        if table.qr_token and table.qr_token not in ('', None):
            continue
        token = secrets.token_urlsafe(16)
        while token in used:
            token = secrets.token_urlsafe(16)
        used.add(token)
        table.qr_token = token
        table.save(update_fields=['qr_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pos', '0001_initial'),
        ('core', '0002_alter_historicalrateplan_base_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmenucategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional icon key, e.g. burgers, drinks', max_length=40),
        ),
        migrations.AddField(
            model_name='historicalmenuitem',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalmenuitem',
            name='low_stock_at',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalmenuitem',
            name='stock_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='historicalmenuitem',
            name='track_inventory',
            field=models.BooleanField(default=False, help_text='When true, stock_qty is decremented on order send/pay'),
        ),
        migrations.AddField(
            model_name='historicalposorder',
            name='channel',
            field=models.CharField(choices=[('POS', 'Billing POS'), ('WAITER', 'Waiter App'), ('QR', 'QR Ordering'), ('SWIGGY', 'Swiggy'), ('ZOMATO', 'Zomato'), ('OTHER', 'Other')], default='POS', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalposorder',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalposorder',
            name='external_order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Partner order id (Swiggy/Zomato)', max_length=120),
        ),
        migrations.AddField(
            model_name='historicalposorder',
            name='guest_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicalposorder',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='historicalposorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalposorder',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', 'Dine In'), ('TAKEAWAY', 'Takeaway'), ('DELIVERY', 'Delivery'), ('ROOM_SERVICE', 'Room Service'), ('QR', 'QR Guest Order'), ('AGGREGATOR', 'Swiggy / Zomato')], default='DINE_IN', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalposorder',
            name='subtotal_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=14),
        ),
        migrations.AddField(
            model_name='historicalposorder',
            name='subtotal_amount_currency',
            field=djmoney.models.fields.CurrencyField(default='INR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='historicalposorder',
            name='tax_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=14),
        ),
        migrations.AddField(
            model_name='historicalposorder',
            name='tax_amount_currency',
            field=djmoney.models.fields.CurrencyField(default='INR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='historicalposorder',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name='historicalposorderitem',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalpostable',
            name='qr_token',
            field=models.CharField(db_index=True, default=cloud_pos.models._qr_token, max_length=64),
        ),
        migrations.AddField(
            model_name='historicalpostable',
            name='section',
            field=models.CharField(blank=True, help_text='Floor / section label', max_length=80),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional icon key, e.g. burgers, drinks', max_length=40),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='low_stock_at',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=12),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='track_inventory',
            field=models.BooleanField(default=False, help_text='When true, stock_qty is decremented on order send/pay'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='channel',
            field=models.CharField(choices=[('POS', 'Billing POS'), ('WAITER', 'Waiter App'), ('QR', 'QR Ordering'), ('SWIGGY', 'Swiggy'), ('ZOMATO', 'Zomato'), ('OTHER', 'Other')], default='POS', max_length=20),
        ),
        migrations.AddField(
            model_name='posorder',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='posorder',
            name='external_order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Partner order id (Swiggy/Zomato)', max_length=120),
        ),
        migrations.AddField(
            model_name='posorder',
            name='guest_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='posorder',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='posorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='posorder',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', 'Dine In'), ('TAKEAWAY', 'Takeaway'), ('DELIVERY', 'Delivery'), ('ROOM_SERVICE', 'Room Service'), ('QR', 'QR Guest Order'), ('AGGREGATOR', 'Swiggy / Zomato')], default='DINE_IN', max_length=20),
        ),
        migrations.AddField(
            model_name='posorder',
            name='subtotal_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=14),
        ),
        migrations.AddField(
            model_name='posorder',
            name='subtotal_amount_currency',
            field=djmoney.models.fields.CurrencyField(default='INR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='posorder',
            name='tax_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=14),
        ),
        migrations.AddField(
            model_name='posorder',
            name='tax_amount_currency',
            field=djmoney.models.fields.CurrencyField(default='INR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='posorder',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name='posorderitem',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='postable',
            name='qr_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.RunPython(_backfill_qr_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='postable',
            name='qr_token',
            field=models.CharField(db_index=True, default=cloud_pos.models._qr_token, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='postable',
            name='section',
            field=models.CharField(blank=True, help_text='Floor / section label', max_length=80),
        ),
        migrations.AlterField(
            model_name='historicalposorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SENT', 'Sent to Kitchen'), ('SERVED', 'Served'), ('BILLED', 'Billed'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('HELD', 'On Hold')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SENT', 'Sent to Kitchen'), ('SERVED', 'Served'), ('BILLED', 'Billed'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('HELD', 'On Hold')], default='OPEN', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalDeliveryPartnerOrder',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('partner', models.CharField(choices=[('SWIGGY', 'Swiggy'), ('ZOMATO', 'Zomato')], max_length=20)),
                ('partner_order_id', models.CharField(max_length=120)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('items_json', models.JSONField(blank=True, default=list)),
                ('total_amount_currency', djmoney.models.fields.CurrencyField(default='INR', editable=False, max_length=3)),
                ('total_amount', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=14)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('DISPATCHED', 'Dispatched'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pos_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cloud_pos.posorder')),
                ('property', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.property')),
            ],
            options={
                'verbose_name': 'historical delivery partner order',
                'verbose_name_plural': 'historical delivery partner orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInventoryMovement',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('RECEIVE', 'Stock received'), ('SALE', 'Sold on order'), ('ADJUST', 'Manual adjustment'), ('WASTE', 'Wastage')], default='ADJUST', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cloud_pos.menuitem')),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cloud_pos.posorder')),
            ],
            options={
                'verbose_name': 'historical inventory movement',
                'verbose_name_plural': 'historical inventory movements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('RECEIVE', 'Stock received'), ('SALE', 'Sold on order'), ('ADJUST', 'Manual adjustment'), ('WASTE', 'Wastage')], default='ADJUST', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='cloud_pos.menuitem')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='cloud_pos.posorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryPartnerOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('partner', models.CharField(choices=[('SWIGGY', 'Swiggy'), ('ZOMATO', 'Zomato')], max_length=20)),
                ('partner_order_id', models.CharField(max_length=120)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('items_json', models.JSONField(blank=True, default=list)),
                ('total_amount_currency', djmoney.models.fields.CurrencyField(default='INR', editable=False, max_length=3)),
                ('total_amount', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=14)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('DISPATCHED', 'Dispatched'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('pos_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_partner_order', to='cloud_pos.posorder')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='core.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('property', 'partner', 'partner_order_id')},
            },
        ),
    ]
