# Generated by Django 5.2.9 on 2026-02-17 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_historicalrateplan_base_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('rooms_count', models.PositiveIntegerField(default=0)),
                ('rates_count', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_ads_feeds', to='core.property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelAdsConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('google_hotel_id', models.CharField(blank=True, max_length=100)),
                ('partner_hotel_id', models.CharField(blank=True, max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('commission_model', models.CharField(default='pay_per_conversion', max_length=50)),
                ('last_feed_submitted', models.DateTimeField(blank=True, null=True)),
                ('feed_status', models.CharField(blank=True, max_length=50)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_ads_config', to='core.property')),
            ],
            options={
                'verbose_name': 'Google Hotel Ads Config',
                'verbose_name_plural': 'Google Hotel Ads Configs',
            },
        ),
    ]
