# Generated by Django 5.2.16 on 2026-07-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_deviceregistration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deviceregistration',
            new_name='device_regi_user_id_670449_idx',
            old_name='device_regi_user_id_7c0a1a_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceregistration',
            new_name='device_regi_tenant__d734e3_idx',
            old_name='device_regi_tenant__b8e2c1_idx',
        ),
    ]
