# Generated by Django 5.2.16 on 2026-07-12 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_historicalrateplan_base_rate_and_more'),
        ('tenants', '0004_rename_device_regi_user_id_7c0a1a_idx_device_regi_user_id_670449_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_packages', to='core.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_packages', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tour_packages',
                'ordering': ['name'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
    ]
