# Generated by Django 5.2.9 on 2026-02-17 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_historicalrateplan_base_rate_and_more'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTAListingStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('property_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_statuses', to='integrations.propertyintegration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('LIVE', 'Live'), ('OPTIMIZED', 'Optimized')], default='PENDING', max_length=20)),
                ('provider_property_id', models.CharField(blank=True, max_length=255)),
                ('listing_score', models.PositiveIntegerField(blank=True, help_text='0-100 quality score', null=True)),
                ('optimization_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_projects', to='integrations.integrationplatform')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_projects', to='core.property')),
            ],
            options={
                'unique_together': {('property', 'platform')},
            },
        ),
    ]
