# Generated by Django 5.2.9 on 2026-01-23 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_subscriptionplan_tenant_api_calls_reset_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('revenue', 'Revenue Report'), ('occupancy', 'Occupancy Report'), ('bookings', 'Bookings Report'), ('channel_performance', 'Channel Performance Report'), ('inventory', 'Inventory Report'), ('custom', 'Custom Report')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('fields', models.JSONField(default=list, help_text='List of fields to include in the report')),
                ('filters', models.JSONField(default=dict, help_text='Default filters for the report')),
                ('can_schedule', models.BooleanField(default=True)),
                ('default_schedule', models.CharField(blank=True, help_text='Cron expression for default schedule', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text='Available to all tenants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=10)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Report file expiration date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tenants.tenant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='reports.reporttemplate')),
            ],
            options={
                'db_table': 'generated_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='generated_r_tenant__b0d7c2_idx'), models.Index(fields=['report_type', 'created_at'], name='generated_r_report__2be608_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='daily', max_length=20)),
                ('cron_expression', models.CharField(blank=True, help_text='Cron expression for custom frequency', max_length=100)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('default_filters', models.JSONField(blank=True, default=dict)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses to send report to')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='reports.reporttemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='tenants.tenant')),
            ],
            options={
                'db_table': 'scheduled_reports',
                'ordering': ['next_run_at'],
                'unique_together': {('tenant', 'template', 'frequency')},
            },
        ),
    ]
