# Generated by Django 5.2.16 on 2026-07-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalintegrationplatform',
            name='secret_ref',
            field=models.CharField(blank=True, help_text='OpenBao KV path for platform credentials', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalpropertyintegration',
            name='secret_ref',
            field=models.CharField(blank=True, help_text='OpenBao KV path for this property↔platform credential set', max_length=255),
        ),
        migrations.AddField(
            model_name='integrationplatform',
            name='secret_ref',
            field=models.CharField(blank=True, help_text='OpenBao KV path for platform credentials', max_length=255),
        ),
        migrations.AddField(
            model_name='propertyintegration',
            name='secret_ref',
            field=models.CharField(blank=True, help_text='OpenBao KV path for this property↔platform credential set', max_length=255),
        ),
    ]
