# Generated by Django 5.2.16 on 2026-07-12 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_historicalrateplan_base_rate_and_more'),
        ('tenants', '0004_rename_device_regi_user_id_7c0a1a_idx_device_regi_user_id_670449_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codename', models.CharField(db_index=True, max_length=100, unique=True)),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Capabilities',
                'db_table': 'rbac_capabilities',
                'ordering': ['module', 'action'],
                'indexes': [models.Index(fields=['module', 'action'], name='rbac_capabi_module_0cf4be_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(choices=[('executive', 'Executive'), ('front_office', 'Front Office'), ('revenue', 'Revenue Management'), ('housekeeping', 'Housekeeping'), ('food_beverage', 'Food & Beverage'), ('guest_services', 'Guest Services'), ('engineering', 'Engineering'), ('sales', 'Sales & Events'), ('finance', 'Finance'), ('compliance', 'Compliance & Audit'), ('wellness', 'Spa & Wellness'), ('security', 'Security'), ('other', 'Other')], db_index=True, default='other', max_length=40)),
                ('default_scope', models.CharField(choices=[('tenant', 'Tenant-wide'), ('property', 'Property-scoped')], default='property', help_text='Suggested assignment scope when granting this role', max_length=20)),
                ('is_system', models.BooleanField(default=False, help_text='System roles are seeded and not editable by tenants')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent role for inheritance display', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rbac.role')),
                ('tenant', models.ForeignKey(blank=True, help_text='Null for system roles; set for tenant-custom roles', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbac_roles', to='tenants.tenant')),
            ],
            options={
                'db_table': 'rbac_roles',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_roles', to='rbac.capability')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_capabilities', to='rbac.role')),
            ],
            options={
                'db_table': 'rbac_role_capabilities',
                'unique_together': {('role', 'capability')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='capabilities',
            field=models.ManyToManyField(blank=True, related_name='roles', through='rbac.RoleCapability', to='rbac.capability'),
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_assigned', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, help_text='Null = tenant-wide access for this role', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.property')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rbac.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rbac_user_role_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('role_assigned', 'Role assigned'), ('role_revoked', 'Role revoked'), ('role_updated', 'Role updated'), ('permission_denied', 'Permission denied'), ('capability_checked', 'Capability checked'), ('legacy_migrated', 'Legacy role migrated')], db_index=True, max_length=40)),
                ('capability', models.CharField(blank=True, max_length=100)),
                ('property_id_snapshot', models.BigIntegerField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_actions', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_audit_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'rbac_access_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'event_type', 'created_at'], name='rbac_access_tenant__35388d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant', 'is_active'], name='rbac_roles_tenant__e52a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_system', 'code'], name='rbac_roles_is_syst_b6bbcc_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('code',), name='rbac_role_unique_system_code'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'code'), name='rbac_role_unique_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['user', 'is_active'], name='rbac_user_r_user_id_46f150_idx'),
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['tenant', 'is_active'], name='rbac_user_r_tenant__3e9534_idx'),
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['property', 'is_active'], name='rbac_user_r_propert_d77668_idx'),
        ),
        migrations.AddConstraint(
            model_name='userroleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('property__isnull', False)), fields=('user', 'role', 'tenant', 'property'), name='rbac_assignment_unique_user_role_property'),
        ),
        migrations.AddConstraint(
            model_name='userroleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('property__isnull', True)), fields=('user', 'role', 'tenant'), name='rbac_assignment_unique_user_role_tenantwide'),
        ),
    ]
