# Generated by Django 5.2.9 on 2026-02-17 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_historicalrateplan_base_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gateway', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='core.property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GatewayConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gateway_name', models.CharField(choices=[('razorpay', 'Razorpay'), ('paypal', 'PayPal'), ('ipay88', 'iPay88'), ('airpay', 'Airpay'), ('payswiff', 'PaySwiff'), ('ingenico', 'Ingenico')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('merchant_id', models.CharField(blank=True, max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('pci_compliant', models.BooleanField(default=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gateway_configs', to='core.property')),
            ],
            options={
                'unique_together': {('property', 'gateway_name')},
            },
        ),
    ]
