# Generated by Django 5.2.16 on 2026-07-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewayconfig',
            name='gateway_name',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('payu', 'PayU'), ('paypal', 'PayPal'), ('ipay88', 'iPay88'), ('airpay', 'Airpay'), ('payswiff', 'PaySwiff'), ('ingenico', 'Ingenico')], max_length=50),
        ),
    ]
