# Generated by Django 5.2.16 on 2026-07-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0002_billing_gateways'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayconfig',
            name='secret_ref',
            field=models.CharField(blank=True, help_text='OpenBao KV path, e.g. revnext/tenants/1/properties/2/gateways/razorpay', max_length=255),
        ),
    ]
