# Generated by Django 5.2.16 on 2026-07-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('tenants', '0004_rename_device_regi_user_id_7c0a1a_idx_device_regi_user_id_670449_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenantproductsubscription',
            name='uniq_active_tenant_product_sub',
        ),
        migrations.AlterField(
            model_name='tenantproductsubscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('pending_payment', 'Pending payment'), ('active', 'Active'), ('past_due', 'Past due'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='trial', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='tenantproductsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False), ('status__in', ['trial', 'active', 'past_due', 'pending_payment'])), fields=('tenant', 'product'), name='uniq_active_tenant_product_sub'),
        ),
    ]
